---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-refresh-operator-role
rules:
  # Permissions for the Custom Resource itself
  - apiGroups: ["stable.rk.ai"]
    resources: ["noderefreshes", "noderefreshes/status"]
    verbs: ["get", "list", "watch", "patch"]
  
  # Permissions to manage Nodes (Cordoning)
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch"]
  
  # Permissions for Eviction and Pod health checks
  - apiGroups: ["", "policy"]
    resources: ["pods", "pods/eviction"]
    verbs: ["get", "list", "create"]
  
  # Permissions to check Pod Disruption Budgets
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-refresh-operator-binding
subjects:    #identity lives here
  - kind: ServiceAccount
    name: node-refresh-operator
    namespace: node-refresh
roleRef:
  kind: ClusterRole
  name: node-refresh-operator-role
  apiGroup: rbac.authorization.k8s.io